#ifndef COS_CPP_SDK_V5_SRC_INTERNAL_JSON_VALUE_H_
#define COS_CPP_SDK_V5_SRC_INTERNAL_JSON_VALUE_H_

#include <stdint.h>

#include <cctype>
#include <cerrno>
#include <cstdlib>
#include <cstring>
#include <iomanip>
#include <limits>
#include <map>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

namespace qcloud_cos {
namespace internal {

// A deliberately small JSON value/parser used for configuration and
// checkpoint files.  It keeps object insertion order so checkpoint files
// generated by older SDK versions retain their MD5 compatibility.
class JsonValue {
 public:
  enum class Type { Null, Bool, Number, String, Object, Array };
  using Object = std::vector<std::pair<std::string, JsonValue>>;
  using Array = std::vector<JsonValue>;

  JsonValue() : m_type(Type::Null), m_bool(false) {}

  static JsonValue Bool(bool value) {
    JsonValue result;
    result.m_type = Type::Bool;
    result.m_bool = value;
    return result;
  }

  static JsonValue Number(const std::string& value) {
    JsonValue result;
    result.m_type = Type::Number;
    result.m_number = value;
    return result;
  }

  static JsonValue String(const std::string& value) {
    JsonValue result;
    result.m_type = Type::String;
    result.m_string = value;
    return result;
  }

  static JsonValue ObjectValue() {
    JsonValue result;
    result.m_type = Type::Object;
    return result;
  }

  static JsonValue ArrayValue() {
    JsonValue result;
    result.m_type = Type::Array;
    return result;
  }

  Type type() const { return m_type; }
  bool IsNull() const { return m_type == Type::Null; }
  bool IsBool() const { return m_type == Type::Bool; }
  bool IsNumber() const { return m_type == Type::Number; }
  bool IsString() const { return m_type == Type::String; }
  bool IsObject() const { return m_type == Type::Object; }
  bool IsArray() const { return m_type == Type::Array; }

  bool AsBool(bool* value) const {
    if (!value || !IsBool()) return false;
    *value = m_bool;
    return true;
  }

  bool AsString(std::string* value) const {
    if (!value || !IsString()) return false;
    *value = m_string;
    return true;
  }

  bool AsUInt64(uint64_t* value) const {
    if (!value || !IsNumber() || m_number.empty()) return false;
    if (m_number[0] == '-' || m_number.find_first_of(".eE") != std::string::npos) {
      return false;
    }
    char* end = nullptr;
    errno = 0;
    unsigned long long parsed = std::strtoull(m_number.c_str(), &end, 10);
    if (errno == ERANGE || end == m_number.c_str() || *end != '\0') {
      return false;
    }
    *value = static_cast<uint64_t>(parsed);
    return true;
  }

  const JsonValue* Find(const std::string& key) const {
    if (!IsObject()) return nullptr;
    for (const auto& item : m_object) {
      if (item.first == key) return &item.second;
    }
    return nullptr;
  }

  JsonValue* Find(const std::string& key) {
    if (!IsObject()) return nullptr;
    for (auto& item : m_object) {
      if (item.first == key) return &item.second;
    }
    return nullptr;
  }

  void Set(const std::string& key, const JsonValue& value) {
    if (!IsObject()) {
      m_type = Type::Object;
      m_object.clear();
    }
    JsonValue* old_value = Find(key);
    if (old_value) {
      *old_value = value;
    } else {
      m_object.emplace_back(key, value);
    }
  }

  const Object& object() const { return m_object; }
  const Array& array() const { return m_array; }

  void Add(const JsonValue& value) {
    if (!IsArray()) {
      m_type = Type::Array;
      m_array.clear();
    }
    m_array.push_back(value);
  }

  static bool Parse(const std::string& input, JsonValue* value,
                    std::string* error) {
    if (!value) return false;
    Parser parser(input, error);
    if (!parser.ParseValue(value)) return false;
    parser.SkipWhitespace();
    if (!parser.AtEnd()) {
      parser.SetError("unexpected characters after JSON value");
      return false;
    }
    return true;
  }

  std::string Serialize() const {
    std::ostringstream output;
    SerializeTo(&output);
    return output.str();
  }

 private:
  class Parser {
   public:
    Parser(const std::string& input, std::string* error)
        : m_input(input), m_error(error), m_pos(0) {}

    bool AtEnd() const { return m_pos >= m_input.size(); }

    void SkipWhitespace() {
      while (!AtEnd() && std::isspace(static_cast<unsigned char>(m_input[m_pos]))) {
        ++m_pos;
      }
    }

    void SetError(const std::string& message) {
      if (m_error && m_error->empty()) {
        *m_error = message + " at offset " + std::to_string(m_pos);
      }
    }

    bool ParseValue(JsonValue* value) {
      SkipWhitespace();
      if (AtEnd()) {
        SetError("unexpected end of input");
        return false;
      }
      switch (m_input[m_pos]) {
        case 'n': return ParseLiteral("null", JsonValue(), value);
        case 't': return ParseLiteral("true", JsonValue::Bool(true), value);
        case 'f': return ParseLiteral("false", JsonValue::Bool(false), value);
        case '"': {
          std::string string_value;
          if (!ParseString(&string_value)) return false;
          *value = JsonValue::String(string_value);
          return true;
        }
        case '{': return ParseObject(value);
        case '[': return ParseArray(value);
        default: return ParseNumber(value);
      }
    }

   private:
    bool ParseLiteral(const char* literal, const JsonValue& value,
                      JsonValue* output) {
      const size_t length = std::strlen(literal);
      if (m_input.compare(m_pos, length, literal) != 0) {
        SetError("invalid literal");
        return false;
      }
      m_pos += length;
      *output = value;
      return true;
    }

    bool ParseString(std::string* output) {
      if (AtEnd() || m_input[m_pos] != '"') {
        SetError("expected string");
        return false;
      }
      ++m_pos;
      output->clear();
      while (!AtEnd()) {
        const unsigned char c = static_cast<unsigned char>(m_input[m_pos++]);
        if (c == '"') return true;
        if (c < 0x20) {
          SetError("control character in string");
          return false;
        }
        if (c != '\\') {
          output->push_back(static_cast<char>(c));
          continue;
        }
        if (AtEnd()) {
          SetError("unterminated escape sequence");
          return false;
        }
        const char escaped = m_input[m_pos++];
        switch (escaped) {
          case '"': output->push_back('"'); break;
          case '\\': output->push_back('\\'); break;
          case '/': output->push_back('/'); break;
          case 'b': output->push_back('\b'); break;
          case 'f': output->push_back('\f'); break;
          case 'n': output->push_back('\n'); break;
          case 'r': output->push_back('\r'); break;
          case 't': output->push_back('\t'); break;
          case 'u':
            if (!ParseUnicodeEscape(output)) return false;
            break;
          default:
            SetError("invalid escape sequence");
            return false;
        }
      }
      SetError("unterminated string");
      return false;
    }

    bool ParseUnicodeEscape(std::string* output) {
      if (m_pos + 4 > m_input.size()) {
        SetError("invalid unicode escape");
        return false;
      }
      unsigned int code_point = 0;
      for (size_t i = 0; i < 4; ++i) {
        const char c = m_input[m_pos++];
        code_point <<= 4;
        if (c >= '0' && c <= '9') code_point += c - '0';
        else if (c >= 'a' && c <= 'f') code_point += c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') code_point += c - 'A' + 10;
        else {
          SetError("invalid unicode escape");
          return false;
        }
      }
      AppendUtf8(code_point, output);
      return true;
    }

    static void AppendUtf8(unsigned int code_point, std::string* output) {
      if (code_point <= 0x7f) {
        output->push_back(static_cast<char>(code_point));
      } else if (code_point <= 0x7ff) {
        output->push_back(static_cast<char>(0xc0 | (code_point >> 6)));
        output->push_back(static_cast<char>(0x80 | (code_point & 0x3f)));
      } else {
        output->push_back(static_cast<char>(0xe0 | (code_point >> 12)));
        output->push_back(static_cast<char>(0x80 | ((code_point >> 6) & 0x3f)));
        output->push_back(static_cast<char>(0x80 | (code_point & 0x3f)));
      }
    }

    bool ParseObject(JsonValue* output) {
      ++m_pos;  // {
      JsonValue object = JsonValue::ObjectValue();
      SkipWhitespace();
      if (!AtEnd() && m_input[m_pos] == '}') {
        ++m_pos;
        *output = object;
        return true;
      }
      while (!AtEnd()) {
        SkipWhitespace();
        std::string key;
        if (!ParseString(&key)) return false;
        SkipWhitespace();
        if (AtEnd() || m_input[m_pos] != ':') {
          SetError("expected ':' after object key");
          return false;
        }
        ++m_pos;
        JsonValue value;
        if (!ParseValue(&value)) return false;
        object.Set(key, value);
        SkipWhitespace();
        if (!AtEnd() && m_input[m_pos] == '}') {
          ++m_pos;
          *output = object;
          return true;
        }
        if (AtEnd() || m_input[m_pos] != ',') {
          SetError("expected ',' or '}' in object");
          return false;
        }
        ++m_pos;
      }
      SetError("unterminated object");
      return false;
    }

    bool ParseArray(JsonValue* output) {
      ++m_pos;  // [
      JsonValue array = JsonValue::ArrayValue();
      SkipWhitespace();
      if (!AtEnd() && m_input[m_pos] == ']') {
        ++m_pos;
        *output = array;
        return true;
      }
      while (!AtEnd()) {
        JsonValue value;
        if (!ParseValue(&value)) return false;
        array.Add(value);
        SkipWhitespace();
        if (!AtEnd() && m_input[m_pos] == ']') {
          ++m_pos;
          *output = array;
          return true;
        }
        if (AtEnd() || m_input[m_pos] != ',') {
          SetError("expected ',' or ']' in array");
          return false;
        }
        ++m_pos;
      }
      SetError("unterminated array");
      return false;
    }

    bool ParseNumber(JsonValue* output) {
      const size_t begin = m_pos;
      if (m_input[m_pos] == '-') ++m_pos;
      if (AtEnd()) {
        SetError("invalid number");
        return false;
      }
      if (m_input[m_pos] == '0') {
        ++m_pos;
      } else if (m_input[m_pos] >= '1' && m_input[m_pos] <= '9') {
        while (!AtEnd() && std::isdigit(static_cast<unsigned char>(m_input[m_pos]))) ++m_pos;
      } else {
        SetError("invalid number");
        return false;
      }
      if (!AtEnd() && m_input[m_pos] == '.') {
        ++m_pos;
        if (AtEnd() || !std::isdigit(static_cast<unsigned char>(m_input[m_pos]))) {
          SetError("invalid number fraction");
          return false;
        }
        while (!AtEnd() && std::isdigit(static_cast<unsigned char>(m_input[m_pos]))) ++m_pos;
      }
      if (!AtEnd() && (m_input[m_pos] == 'e' || m_input[m_pos] == 'E')) {
        ++m_pos;
        if (!AtEnd() && (m_input[m_pos] == '+' || m_input[m_pos] == '-')) ++m_pos;
        if (AtEnd() || !std::isdigit(static_cast<unsigned char>(m_input[m_pos]))) {
          SetError("invalid number exponent");
          return false;
        }
        while (!AtEnd() && std::isdigit(static_cast<unsigned char>(m_input[m_pos]))) ++m_pos;
      }
      *output = JsonValue::Number(m_input.substr(begin, m_pos - begin));
      return true;
    }

    const std::string& m_input;
    std::string* m_error;
    size_t m_pos;
  };

  static void AppendEscaped(const std::string& value, std::ostringstream* output) {
    *output << '"';
    for (unsigned char c : value) {
      switch (c) {
        case '"': *output << "\\\""; break;
        case '\\': *output << "\\\\"; break;
        case '\b': *output << "\\b"; break;
        case '\f': *output << "\\f"; break;
        case '\n': *output << "\\n"; break;
        case '\r': *output << "\\r"; break;
        case '\t': *output << "\\t"; break;
        default:
          if (c < 0x20) {
            *output << "\\u" << std::hex << std::setw(4) << std::setfill('0')
                    << static_cast<unsigned int>(c) << std::dec << std::setfill('0');
          } else {
            output->put(static_cast<char>(c));
          }
      }
    }
    *output << '"';
  }

  void SerializeTo(std::ostringstream* output) const {
    switch (m_type) {
      case Type::Null: *output << "null"; break;
      case Type::Bool: *output << (m_bool ? "true" : "false"); break;
      case Type::Number: *output << m_number; break;
      case Type::String: AppendEscaped(m_string, output); break;
      case Type::Object:
        *output << '{';
        for (size_t i = 0; i < m_object.size(); ++i) {
          if (i != 0) *output << ',';
          AppendEscaped(m_object[i].first, output);
          *output << ':';
          m_object[i].second.SerializeTo(output);
        }
        *output << '}';
        break;
      case Type::Array:
        *output << '[';
        for (size_t i = 0; i < m_array.size(); ++i) {
          if (i != 0) *output << ',';
          m_array[i].SerializeTo(output);
        }
        *output << ']';
        break;
    }
  }

  Type m_type;
  bool m_bool;
  std::string m_number;
  std::string m_string;
  Object m_object;
  Array m_array;
};

}  // namespace internal
}  // namespace qcloud_cos

#endif  // COS_CPP_SDK_V5_SRC_INTERNAL_JSON_VALUE_H
